### ISSUE TITLE
Cover art for v1

### ISSUE THREAD

**Issue by ghost** [vtduncan/dat-protocol-guide#15]

**Comment by ghost** [comment]
![how_dat_works_cover_1600](https://user-images.githubusercontent.com/34459172/51425154-245a6f00-1c3d-11e9-81b3-9f71c0ed71ac.jpg)

Oh boy, this one falls hard into the uncanny valley of “can’t tell whether trying to do bad 3d shtick or just not very good at blender”. Hope someone on the internet gets a giggle out of this, but I’m glad it’s not going into the guide :stuck_out_tongue_closed_eyes:

Model is based on Ben Simonds’ Jungle Temple from [Blender Master Class](https://nostarch.com/blendermasterclass).

**Comment by joehand** [comment]
Haha thats amazing.
