### ISSUE TITLE
Clarification of hex and decimal

### ISSUE THREAD

**Issue by dariusk** [vtduncan/dat-protocol-guide#2]
(Hi! I'm working with Code for Science & Society as their Mozilla Fellow so I'm reading through this doc and thought I'd put notes on it here as I'm trying to learn the protocol. REALLY great job overall btw.)

I notice that you are choosing to show decimal representation of individual bytes rather than their hex, which mostly makes things very clear. However there are some parts where multiple bytes act as 16-bit word and suddenly it gets confusing. For example, this image confused me:

![image](https://user-images.githubusercontent.com/266454/50494227-cf795f00-09d6-11e9-8bdb-1cd50249d270.png)

I didn't realize that `12 210` was just the decimal readout of `0c d2`. I was like, is that octal? Base 3? What's going on? Basically the connection between `12 210` and `3282` is unclear. If the image said `0c d2` instead that would be instantly clear but then it would conflict with everything else you have going on in the document.

Maybe annotate the image like so?

![image](https://user-images.githubusercontent.com/266454/50494592-11a3a000-09d9-11e9-978f-3623148beedd.png)

I would have made a PR but then I realized that you do have a style going so I thought I'd pose this as more of a question.

**Comment by ghost** [comment]
Thanks, this is a really clear explanation of why this is confusing! Awesome feedback!

I’m going to try adding an aside to explain this the first time it appears, similar to the concept you have drawn.

**Comment by ghost** [comment]
Ok, I’ve added these three asides to explain the decimal notation as each new concept is needed.

![aside_1](https://user-images.githubusercontent.com/34459172/50501859-30c92d00-0ac0-11e9-9cac-d73097bee510.png)

![aside_2](https://user-images.githubusercontent.com/34459172/50501860-3161c380-0ac0-11e9-9b6b-e20722e3f132.png)

![aside_3](https://user-images.githubusercontent.com/34459172/50501861-3161c380-0ac0-11e9-97b4-545b3a419170.png)

@dariusk, Do you think these would have helped you understand this more easily on your first read through? Is there anything you would add or change?

**Comment by dariusk** [comment]
Yes that is great and fully addresses my issue!

Since I've been thinking about it there is only other thing I would ask for. In the following representation of an IP address:

![image](https://user-images.githubusercontent.com/266454/50504943-ac29d080-0a25-11e9-96f2-8209cfb64c45.png)

it might make more sense if there were a `.` between the numbers. So it would look something like `[0].[0].[0].[0]`. Just to be clear that each byte represents one of the 4 fields in the IP address. But maybe that is too nitpicky and people can figure that out from context.

**Comment by ghost** [comment]
Great! I’ll try out the IP address formatting suggestion and include that too if works ok visually.
