### ISSUE TITLE
DO THE RELEASE!

### ISSUE THREAD

**Issue by ghost** [vtduncan/dat-protocol-guide#21]
- [x] Update visual index
- [x] Remove the WIP labels
- [x] Publish the blog post
- [x] Spread the word
- [x] Eat cake

**Comment by joehand** [comment]
:cake: !

**Comment by ghost** [comment]
![cake](https://user-images.githubusercontent.com/34459172/51508342-9b6c4f00-1e59-11e9-95b3-60c5fd44b2a2.jpg)

Release complete!
