### ISSUE TITLE
Peers record always the same even after IP list updates?

### ISSUE THREAD

**Issue by dariusk** [vtduncan/dat-protocol-guide#3]
In this diagram:

![image](https://user-images.githubusercontent.com/266454/50494966-30a33180-09db-11e9-9303-b365cc1e1cc8.png)

The discovery server always returns `WM6...wzS`, which makes sense to me for the first two, but is there a reason it should be exactly the same after another server joins and leaves? I guess assuming all things being equal the join/leave would result in the peers record being the same at the end, but that might lead someone to believe that the peers record is some kind of immutable value. It might make more sense to have the peer NOT leave, have it return a new peer record, then have the peer leave, and the peer record then reverting back to `WM6...wzS`.

(Also I might be totally off base here as well! This is just based on my understanding as a first time reader.)

**Comment by ghost** [comment]
Thanks @dariusk, this is really helpful to hear about details like this that are confusing!

I did some quick testing and in practice the peers string does change each time, so I’m going to update this figure to reflect that.

**Comment by ghost** [comment]
Done in 0931d5e!
